/* Population figures are rounded 2024 estimates and are here for context,
   not precision. Check them before quoting them anywhere that matters. */
export default [
  {
    slug: "greece", region: "europe", name: "Greece",
    capital: "Athens", population: "10.4 million", currency: "Euro (EUR)",
    language: "Greek", timezone: "EET, UTC+2", flight: "3h 45m from London",
    blurb: "Six thousand islands, about two hundred of them inhabited, and a mainland most visitors never leave Athens to see. The islands split into groups that barely resemble each other.",
    whenToGo: "May, June and late September. July and August are hot and full.",
  },
  {
    slug: "portugal", region: "europe", name: "Portugal",
    capital: "Lisbon", population: "10.6 million", currency: "Euro (EUR)",
    language: "Portuguese", timezone: "WET, UTC+0", flight: "2h 40m from London",
    blurb: "A long Atlantic coast with a different character every hundred miles, from the surf beaches of the north to the limestone cliffs of the Algarve.",
    whenToGo: "April to June, and September to October.",
  },
  {
    slug: "norway", region: "europe", name: "Norway",
    capital: "Oslo", population: "5.6 million", currency: "Norwegian krone (NOK)",
    language: "Norwegian", timezone: "CET, UTC+1", flight: "2h 10m from London to Oslo",
    blurb: "Expensive, empty and worth it. A third of the country sits above the Arctic Circle, which is where the light does things it does nowhere else.",
    whenToGo: "June and July for the midnight sun. February for aurora and snow.",
  },
  {
    slug: "united-kingdom", region: "europe", name: "United Kingdom",
    capital: "London", population: "68.3 million", currency: "Pound sterling (GBP)",
    language: "English", timezone: "GMT, UTC+0", flight: "No flight required",
    blurb: "Three national parks within four hours of most of the population, a coastline nobody is more than seventy miles from, and weather that makes planning pointless. The best-value week on this site.",
    whenToGo: "May and September. School holidays double the price of everything.",
  },
  {
    slug: "thailand", region: "asia", name: "Thailand",
    capital: "Bangkok", population: "71.7 million", currency: "Thai baht (THB)",
    language: "Thai", timezone: "ICT, UTC+7", flight: "11h 30m from London",
    blurb: "Two coasts with opposite weather, so there is always one side of the country worth being on. The Andaman side has the limestone, the Gulf side has the calmer water.",
    whenToGo: "November to March on the Andaman coast.",
  },
  {
    slug: "indonesia", region: "asia", name: "Indonesia",
    capital: "Jakarta", population: "281 million", currency: "Indonesian rupiah (IDR)",
    language: "Indonesian", timezone: "WIB to WIT, UTC+7 to UTC+9", flight: "16h from London to Denpasar",
    blurb: "Seventeen thousand islands, and most visitors see one of them. Even on Bali, two hours inland is a different place entirely.",
    whenToGo: "April to October, the dry season.",
  },
  {
    slug: "maldives", region: "asia", name: "Maldives",
    capital: "Malé", population: "525,000", currency: "Maldivian rufiyaa (MVR)",
    language: "Dhivehi", timezone: "MVT, UTC+5", flight: "10h 30m from London",
    blurb: "Twenty-six atolls, about two hundred inhabited islands, and roughly the same number given over entirely to resorts. Staying on a local island costs a tenth as much and the reef is the same reef.",
    whenToGo: "November to April, the dry season.",
  },
  {
    slug: "morocco", region: "africa", name: "Morocco",
    capital: "Rabat", population: "37.5 million", currency: "Moroccan dirham (MAD)",
    language: "Arabic and Amazigh", timezone: "UTC+1", flight: "3h 30m from London",
    blurb: "Coast, mountains and desert inside a country you can cross in a day, and the shortest flight on this site to somewhere that feels genuinely far away.",
    whenToGo: "March to May, and October to November. The desert is unbearable in July.",
  },
  {
    slug: "united-states", region: "americas", name: "United States",
    capital: "Washington, D.C.", population: "335 million", currency: "US dollar (USD)",
    language: "English", timezone: "UTC-5 to UTC-10", flight: "8h 30m from London to Orlando",
    blurb: "Too big to generalise about. The only sensible approach is to pick one state, or one road, and ignore the rest.",
    whenToGo: "Depends entirely where. Florida is best from November to April.",
  },
  {
    slug: "new-zealand", region: "oceania", name: "New Zealand",
    capital: "Wellington", population: "5.3 million", currency: "New Zealand dollar (NZD)",
    language: "English and te reo Māori", timezone: "NZST, UTC+12",
    flight: "24h from London, minimum one stop",
    blurb: "Two islands, five million people, and more empty road than anywhere else on this list. The South Island is the reason to make the flight.",
    whenToGo: "December to March. Fiordland is wet in all of them.",
  },
];
