/* Every stay gets one review page, nested under the first type in its
   `types` list: /stays/{first-type}/{slug}/. That URL is the only one used
   anywhere on the site, so a stay tagged with four types still has a single
   canonical address. Order `types` with the defining feature first.

   */
export default [
  { slug: "cave-house-imerovigli", name: "Cave House, Imerovigli", place: "santorini",
    kind: "Airbnb", types: ["pool", "beach"], sleeps: 4, price: 290, rating: 4,
    stayed: "September 2024", nights: 5,
    summary: "Cut back into the cliff, with a plunge pool on the terrace and 300 steps down to the water.",
    review: [
      "The terrace is the room. Everything indoors is a windowless barrel vault carved into volcanic rock, which sounds grim and is actually the coolest place on the island at four in the afternoon. You will spend daylight hours outside and be grateful for the cave at night.",
      "The plunge pool is genuinely plunge sized, about three strokes across, and it faces the caldera. The 300 steps down to the water are a real 300 steps and there is no lift, so factor that in if anyone in the group struggles with knees.",
      "Noise carries along the cliff in a way I did not expect. You hear other people's terraces clearly, which on the two nights someone above us had a party mattered a lot.",
    ],
    verdict: "The view is the product and it delivers. Take the steps seriously and do not expect quiet.",
    good: ["Caldera view from the pool", "Cool indoors without air conditioning", "Twenty minutes' walk from Oia on the cliff path"],
    bad: ["Sound travels between terraces", "300 steps to the sea, no lift", "No parking within five minutes"] },

  { slug: "canaves-epitome", name: "Canaves Epitome", place: "santorini",
    kind: "Hotel suite", types: ["hotel", "pool"], sleeps: 2, price: 980, rating: 4,
    stayed: "September 2024", nights: 2,
    summary: "Private pool on the caldera edge, dinner laid out on the terrace at sundown.",
    review: [
      "Two nights here as a splurge at the end of a cheaper week, which I would recommend as a structure. The room is enormous and the private pool is heated, which matters more in late September than it sounds.",
      "Service is the thing you are paying for. Everything appears without being asked for, and the in-room dinner is genuinely good rather than merely convenient.",
      "It is in Oia, so the sunset crowd is on your doorstep and the walk in from the car park with luggage is unpleasant.",
    ],
    verdict: "Absurd money, and it does what absurd money is supposed to do. Two nights, not seven.",
    good: ["Heated private pool", "Dinner on the terrace is worth booking", "Staff anticipate everything"],
    bad: ["Oia is very busy from five o'clock", "Awkward luggage walk", "Breakfast is an extra"] },

  { slug: "villa-helidona", name: "Villa Helidona", place: "nydri",
    kind: "Villa", types: ["pool", "rural"], sleeps: 8, price: 210, rating: 5,
    stayed: "June 2025", nights: 10,
    image: "helidona-pool",
    gallery: ["helidona-pool"],
    summary: "Up the hill behind Nydri, with a private pool, a vine pergola and the whole bay laid out below.",
    review: [
      "It is fifteen minutes above the town on a road that gets narrower than you would like, and that climb is the entire reason the place works. The bay is spread out underneath you, the noise of the harbour does not reach, and the temperature at eight in the evening is about four degrees cooler than down at sea level.",
      "The pool is a proper length rather than a plunge, with a dolphin mosaic on the floor that the children were unreasonably invested in. There is a vine-covered pergola along one side that gives you shade from about eleven onwards, which matters more than the pool does in July.",
      "A chocolate labrador belongs to the owners and considers the pool terrace hers. Nobody mentioned this in advance and it turned out to be the best thing about the week. If you do not want a dog around, this is not your villa.",
      "The road down into Nydri is the one real drawback. It is fine in daylight and unpleasant after dinner and two glasses of wine, so work out who is driving before you go out.",
    ],
    verdict: "The best value villa I have booked anywhere. Ten nights, eight people, and the view never got old.",
    good: ["Private pool with the bay below it", "Pergola shade from mid-morning", "Cooler up here than in town", "The dog"],
    bad: ["Narrow road up, worse after dark", "A car is essential", "Nearest shop is down in Nydri"] },

  { slug: "plaka-beach-rooms", name: "Plaka Beach Rooms", place: "naxos",
    kind: "Guesthouse", types: ["beach", "hotel"], sleeps: 3, price: 95, rating: 4,
    stayed: "June 2024", nights: 6,
    summary: "Simple rooms behind the dunes on a beach that runs for four kilometres.",
    review: [
      "A family runs it and it shows in the small things. Fresh bread appears at eight, the bikes are free, and somebody moves the sun loungers to follow the shade without being asked.",
      "Plaka itself is the point. Four kilometres of sand, no development, and enough of it that even in June you can walk five minutes and be alone.",
      "Rooms are plain and the walls are thin. This is not a design hotel and does not pretend to be.",
    ],
    verdict: "The best value on this site. Book it before the internet notices.",
    good: ["Straight onto an empty beach", "Free bikes", "Under a hundred a night in June"],
    bad: ["Thin walls", "Basic rooms", "Car needed for the rest of the island"] },

  { slug: "casa-do-carrasco", name: "Casa do Carrasco, Carvoeiro", place: "algarve",
    kind: "Airbnb", types: ["pool", "beach"], sleeps: 6, price: 180, rating: 5,
    stayed: "October 2024", nights: 7,
    summary: "Whitewashed house with a roof terrace, ten minutes from the cliff path.",
    review: [
      "Three bedrooms, a shaded courtyard and a roof terrace that gets sun from about ten until it goes down. In October that meant every meal outside for a week.",
      "The cliff path east towards Praia da Marinha starts ten minutes from the door, which is the whole reason to stay in Carvoeiro rather than somewhere with a bigger beach.",
      "The pool is shared with two other houses. In October we never once saw anyone else in it. In August that would be a different review.",
    ],
    verdict: "Right house, right position, right month. Go in October.",
    good: ["Cliff path from the door", "Roof terrace holds sun all day", "Thirty a head with six people"],
    bad: ["Pool is shared", "Steep walk back up from the beach", "Very quiet out of season, which cuts both ways"] },

  { slug: "rorbu-14-reine", name: "Rorbu 14, Reine", place: "lofoten",
    kind: "Airbnb", types: ["sauna", "rural"], sleeps: 4, price: 210, rating: 5,
    stayed: "June 2024", nights: 4,
    summary: "Restored 1940s fishing cabin in red pine, with a ladder into the fjord.",
    review: [
      "A working rorbu that somebody has quietly modernised without stripping out what made it worth keeping. Original pine, a stove that actually heats the place, and a ladder off the deck straight into the water.",
      "The sauna is shared between four cabins and there is a booking sheet on the door, which sounds annoying and works perfectly. Sauna then fjord, at one in the morning, in full daylight, is the reason to come to Lofoten in June.",
      "Blackout blinds are provided and you will need them. The sun does not set and your body does not care that you know that.",
    ],
    verdict: "The best night's stay on this site. Come in June and accept you will not sleep much.",
    good: ["Ladder into the fjord from the deck", "Shared sauna, well run", "Midnight sun from the deck"],
    bad: ["You will not sleep properly", "Nearest shop is fifteen minutes", "Norway prices for everything else"] },

  { slug: "hattvika-lodge", name: "Hattvika Lodge", place: "lofoten",
    kind: "Lodge", types: ["hotel", "sauna", "rural"], sleeps: 6, price: 640, rating: 4,
    stayed: "June 2024", nights: 2,
    summary: "Glass gable facing Vestfjorden, sauna cut into the rock behind.",
    review: [
      "The architecture is the draw. A wall of glass facing west down the fjord, and a sauna dug into the hillside so you look out at the water from inside it.",
      "It is set up for people who want to be guided, and the ski touring and fishing they arrange are well run. If you only want a bed you are overpaying substantially.",
      "Breakfast is excellent and included, which given Norwegian food prices is a bigger deal than it sounds.",
    ],
    verdict: "Worth it if you use what they organise. Otherwise take the rorbu for a third of the money.",
    good: ["Sauna built into the rock", "Guiding is genuinely good", "Breakfast included"],
    bad: ["Expensive if you self-guide", "Feels like a hotel, not a cabin", "Books up a year ahead in winter"] },

  { slug: "shepherds-hut-trevose", name: "The Shepherd's Hut, Trevose Head", place: "cornwall",
    kind: "Shepherd's hut", types: ["hot-tub", "rural"], sleeps: 2, price: 145, rating: 4,
    stayed: "May 2025", nights: 3,
    summary: "One field back from the coast path, wood-fired tub facing the sea.",
    review: [
      "Small in the way these always are, and well enough built that it does not matter. A double at one end, a stove in the middle, and a compost loo in its own shed twenty steps away.",
      "The wood-fired hot tub takes about three hours to get up to temperature, so light it when you arrive rather than when you want it. Facing west means you get the whole sunset from the water.",
      "The coast path is over the wall. Constantine Bay is twenty-five minutes on foot, Booby's Bay ten minutes further and half as busy.",
    ],
    verdict: "The best UK stay I have booked. Go outside school holidays or the price doubles.",
    good: ["Coast path over the wall", "Wood-fired tub facing the sunset", "Genuinely dark at night"],
    bad: ["Compost loo in a separate shed", "Tub takes three hours to heat", "Doubles in price in August"] },

  { slug: "bedruthan-hotel", name: "Bedruthan Hotel", place: "cornwall",
    kind: "Hotel", types: ["hotel", "pool", "beach"], sleeps: 4, price: 220, rating: 3,
    stayed: "May 2025", nights: 2,
    summary: "Clifftop hotel above Mawgan Porth, built for families and honest about it.",
    review: [
      "Set up entirely around children, with supervised clubs, three pools and a lot of noise. If that is what you need it is very good at it, and the sea view rooms are worth the upgrade.",
      "The food is better than it needs to be and the outdoor pool is heated and faces the sea.",
      "As a couple we felt like we had wandered into someone else's holiday. That is our mistake rather than the hotel's.",
    ],
    verdict: "Excellent with children, awkward without them. Know which trip you are booking.",
    good: ["Heated outdoor pool over the sea", "Kids' clubs are properly staffed", "Path down to Mawgan Porth"],
    bad: ["Loud everywhere", "Not a couples' hotel", "Parking fills by four"] },

  { slug: "coed-y-nant", name: "Coed y Nant Cabin", place: "eryri", kind: "Cabin",
    types: ["forest", "hot-tub", "rural"], sleeps: 4, price: 165, rating: 5,
    stayed: "September 2024", nights: 4,
    summary: "Timber cabin under oak canopy, with a tub on the deck and a river below.",
    review: [
      "Under trees the whole way round, which means it is dark by seven and very quiet. The river is loud enough at night to sleep to and low enough in September to swim in.",
      "The tub is electric rather than wood fired, so it is ready when you are. Less romantic and much more practical after a wet day on the Glyderau.",
      "Phone signal is nonexistent and the wifi is slow. This is presented as a feature and after a day I agreed with them.",
    ],
    verdict: "Everything a wet-weather base in Eryri should be. Book the drying room, use it.",
    good: ["River swimming below the deck", "Tub is hot on arrival", "Proper drying room"],
    bad: ["No phone signal at all", "Dark from early evening", "Track in is rough on a low car"] },

  { slug: "llyn-gwynant", name: "Llyn Gwynant Campsite", place: "eryri", kind: "Campsite",
    types: ["camping", "rural"], sleeps: 6, price: 28, rating: 4,
    stayed: "June 2024", nights: 3,
    summary: "Pitch on the lake shore in the Nant Gwynant valley, under Yr Wyddfa.",
    review: [
      "One of the few campsites where the position alone justifies the trip. Pitches run down to the water and the Watkin Path starts a mile up the road.",
      "Facilities are basic and clean. There is a small shop, a fire pit hire scheme and no electric hookup on the lakeside pitches.",
      "It floods. Ask which pitches sit low before you choose, because after two days of rain the bottom of the field is a bog.",
    ],
    verdict: "Twenty-eight pounds for the best view in Wales. Take the higher pitches.",
    good: ["Pitches on the lake shore", "Watkin Path a mile away", "Fires allowed in hired pits"],
    bad: ["Lower field floods", "No hookup lakeside", "Books out months ahead for summer weekends"] },

  { slug: "bothy-glen-feshie", name: "The Bothy at Glen Feshie", place: "cairngorms",
    kind: "Bothy", types: ["rural", "sauna", "forest"], sleeps: 2, price: 190, rating: 5,
    stayed: "May 2025", nights: 3,
    summary: "Stone bothy in old Caledonian pine, with a barrel sauna and a burn to cool off in.",
    review: [
      "Restored rather than rebuilt, so the walls are still two feet of stone and the windows are still small. Warm in about an hour with the stove going.",
      "The pine forest around Glen Feshie is the real thing, hundreds of years old and regenerating properly, and you can walk for a day without crossing a road.",
      "The barrel sauna is fifty metres away by the burn. Sauna, burn, sauna is the whole evening and it does not get old.",
    ],
    verdict: "The closest Britain gets to Norway. Go in May before the midges.",
    good: ["Ancient pine forest from the door", "Barrel sauna by the burn", "Genuinely dark skies"],
    bad: ["Midges from June", "Forty minutes to a shop", "Sleeps two, and only two"] },

  { slug: "bark-house-grizedale", name: "Bark House, Grizedale", place: "lake-district",
    kind: "Cabin", types: ["forest", "hot-tub"], sleeps: 4, price: 210, rating: 4,
    stayed: "October 2024", nights: 3,
    summary: "Cabin in the middle of Grizedale Forest, twenty minutes from Coniston Water.",
    review: [
      "Deep enough into the forest that you drive the last mile on a track and see nobody. Two bedrooms, a wood burner and a wall of glass facing a clearing where deer turn up most mornings.",
      "The hot tub is on a deck at the back with nothing behind it but trees. In October, in the rain, that is the entire holiday.",
      "Grizedale itself is busy with bikes at weekends. Midweek it is empty.",
    ],
    verdict: "Quiet, warm and well positioned for the western lakes. Go midweek.",
    good: ["Genuinely in the forest", "Deer in the clearing most mornings", "Twenty minutes to Coniston"],
    bad: ["Busy with mountain bikers at weekends", "Rough track for the last mile", "No shop nearby"] },

  { slug: "kissimmee-vacation-home", name: "Vacation home, Kissimmee", place: "orlando",
    kind: "Airbnb", types: ["pool"], sleeps: 8, price: 180, rating: 3,
    stayed: "August 2025", nights: 6,
    summary: "Four bedrooms and a screened private pool, fifteen minutes from the parks.",
    review: [
      "Exactly what everyone in Kissimmee rents and priced accordingly. Four bedrooms, two bathrooms, a garage converted into a games room and a screened pool at the back.",
      "The screen matters more than the pool. It keeps out mosquitoes and, at 34 degrees in August, some of the sun.",
      "It is a housing estate of identical houses doing the same thing, so there is no character to it at all. At thirty pounds a head with eight people, that is a reasonable trade.",
    ],
    verdict: "Functional and cheap per head. Nobody comes to Kissimmee for the accommodation.",
    good: ["Private screened pool", "Cheap split between eight", "Fifteen minutes to the parks"],
    bad: ["No character whatsoever", "Car essential", "Resort fees added at checkout"] },

  { slug: "bundhaya-beachfront", name: "Bundhaya Beachfront", place: "koh-lipe",
    kind: "Guesthouse", types: ["beach", "hotel"], sleeps: 2, price: 55, rating: 3,
    stayed: "January 2025", nights: 5,
    summary: "Fan room thirty seconds from Pattaya Beach, no view and no need for one.",
    review: [
      "A basic room in a good position, which on an island this small is the correct trade. Thirty seconds to the sand and two minutes to Walking Street.",
      "Fan only, which is fine in January and would not be in April. The room is clean and nothing in it is new.",
      "Walking Street noise carries until about midnight. Ask for a room at the back.",
    ],
    verdict: "Fine, cheap, well placed. Ask for a back room and do not expect anything else.",
    good: ["Thirty seconds from the beach", "Under sixty pounds in high season", "Central for the boats"],
    bad: ["Noise until midnight", "Fan only", "Tired fittings"] },

  { slug: "munduk-ridge-villa", name: "Munduk Ridge Villa", place: "munduk",
    kind: "Airbnb", types: ["rural", "forest", "pool"], sleeps: 4, price: 75, rating: 5,
    stayed: "June 2023", nights: 5,
    summary: "Open-sided living room facing the valley, with no glass and no need for it.",
    review: [
      "The front of the house is simply missing, which at 800 metres up is comfortable all day and cold enough at night for a blanket. Cloud comes through the room in the mornings.",
      "The pool is small and unheated and looks straight down the valley. Nobody uses it for swimming.",
      "Getting there is a real drive on a real mountain road. Do not attempt it on a scooter with luggage.",
    ],
    verdict: "The best value stay on this site and the part of Bali worth the flight.",
    good: ["Open-sided living room", "Cloud through the house at dawn", "Coffee grown on the slope below"],
    bad: ["Hard drive to reach", "Cold at night", "Nothing open after nine"] },

  { slug: "fehendhoo-beach-house", name: "Fehendhoo Beach House", place: "baa-atoll",
    kind: "Airbnb", types: ["beach"], sleeps: 5, price: 110, rating: 4,
    stayed: "March 2025", nights: 6,
    summary: "A local island rather than a resort, with two bicycles and reef fifty metres out.",
    review: [
      "Fehendhoo has about two hundred residents and one guesthouse strip, and staying here costs roughly a tenth of what the resort across the water charges for the same reef.",
      "It is a Muslim island, so there is no alcohol and there is a designated bikini beach rather than free run of the sand. Neither bothered us, both are worth knowing before booking.",
      "The snorkelling from the house is better than most organised trips, and the manta excursions leave from the harbour at a fraction of resort prices.",
    ],
    verdict: "Same ocean, tenth of the price. Read up on local island etiquette first.",
    good: ["Reef fifty metres from the door", "A tenth of resort prices", "Manta trips from the harbour"],
    bad: ["No alcohol on the island", "Bikini beach only", "Ferry connections are slow and infrequent"] },

  { slug: "erg-chebbi-camp", name: "Desert camp, Erg Chebbi", place: "erg-chebbi",
    kind: "Tented camp", types: ["camping", "rural"], sleeps: 2, price: 70, rating: 4,
    stayed: "November 2023", nights: 1,
    summary: "Rugs, no power after eleven, and the best sky I have stood under.",
    review: [
      "Camel in at sunset, which is a tourist thing to do and also the only sensible way to arrive. The tents are proper canvas with real beds and a shared washblock.",
      "Generator goes off at eleven and that is when it becomes worth the money. No light for a hundred miles in any direction.",
      "Get up before five. The dunes only look like the pictures for about forty minutes and everyone else surfaces at seven.",
    ],
    verdict: "One night is enough and one night is essential. Set an alarm for half four.",
    good: ["No light pollution at all", "Real beds, not mats", "Sunrise from the big ridge"],
    bad: ["Cold at night in winter", "Shared washblock", "Nothing to do after dark, by design"] },

  { slug: "hut-at-hollyford", name: "The Hut at Hollyford", place: "fiordland",
    kind: "Cabin", types: ["rural", "forest"], sleeps: 2, price: 240, rating: 4,
    stayed: "February 2024", nights: 2,
    summary: "Off grid, wood stove, and the last kilometre on foot.",
    review: [
      "Solar and a wood stove, a water butt off the roof, and a track that stops a kilometre short so you carry everything in. That filter is the entire appeal.",
      "It rained for both days, which in Fiordland is the normal condition and makes the waterfalls run. The stove dried everything overnight.",
      "Sandflies. Nobody warns you enough about the sandflies. Bring repellent and then bring more.",
    ],
    verdict: "Worth the carry. Bring twice the insect repellent you think you need.",
    good: ["Genuinely off grid", "Waterfalls at their best in rain", "Nobody else within earshot"],
    bad: ["Kilometre carry with all your gear", "Sandflies are relentless", "No signal for emergencies"] },
];
